name: CI

on:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:
    branches: [ master ]    

jobs:
  web_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
      # https://github.com/subosito/flutter-action
    - uses: subosito/flutter-action@v1.4.0
      with:
        flutter-version: '2.0.2'
        channel: 'stable'
    - name: "Web Build 🔧"
      run: |
        flutter pub get
        flutter build web
    - name: "Web Deploy 🚀"
      # https://github.com/JamesIves/github-pages-deploy-action
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'
        branch: gh-pages
        folder: build/web